version: '3'

services:
  megacoind:
    build:
      context: ./docker-megacoind
      dockerfile: ./Dockerfile
    image: megacoind
    container_name: megacoind
    command:
      -whitebind=172.21.0.10:7951
      -whitelist=172.21.0.13
      -txindex=1
      -rpcbind=172.21.0.10
      -rpcallowip=172.21.0.0/24
      -port=7951
      -rpcport=7952
      -rpcuser=mec 
      -rpcpassword=mec
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.10
    ports:
      - 7951:7951
    expose:
      - 7952
    volumes:
      - /home/megacoin:/data

  mongodb:
    image: mongo:4.4.4-bionic
    container_name: mongodb
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.11
    ports: 
      - 127.0.0.1:27017:27017
    volumes:
      - /home/mongodb:/data/db

  bitcore-node:
    build:
      context: .
      dockerfile: ./Dockerfile.bitcore-node.mec
    image: bitcore-node
    container_name: bitcore-node
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.13 
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - "DB_HOST=mongodb"
      - "MEGACOIN_CONFIG_PATH=/bitcore/bitcore.config.json"
    depends_on:
      - mongodb
      - megacoind

  insight:
    image: insight
    build:
      context: .
      dockerfile: ./Dockerfile.insight.mec
    container_name: insight
    restart: always
    networks:
      insight-net:
        ipv4_address: 172.21.0.14
    ports:
      - 8080:5000
    environment:
      - "ENV=prod"
      - "CHAIN=MEC"
      - "NETWORK=mainnet"
      - "API_PREFIX=https://api.megacoin-mec.cc/api"
    depends_on:
      - bitcore-node

networks:
  insight-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
