#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service btxcore stop || echo "btxcore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "btxcore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "btxcore.service" || echo "btxcore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so btxcore could not be stopped"
fi
